create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'Fermé' check (status in ('Ouvert', 'Fermé')),
  featured_dish text not null,
  tag text not null,
  created_at timestamptz not null default now()
);

alter table public.restaurants add column if not exists phone text;
alter table public.restaurants add column if not exists address text;
alter table public.restaurants add column if not exists position text;
alter table public.restaurants add column if not exists photo_url text;
alter table public.restaurants add column if not exists owner_email text;

alter table public.restaurants enable row level security;

drop policy if exists "Restaurants publics lisibles par tous" on public.restaurants;
create policy "Restaurants publics lisibles par tous"
  on public.restaurants
  for select
  using (true);

drop policy if exists "Restaurants administrables en démonstration" on public.restaurants;
create policy "Restaurants administrables en démonstration"
  on public.restaurants for all using (true) with check (true);


create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists menus_one_active_per_restaurant
  on public.menus (restaurant_id)
  where is_active = true;

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  menu_id bigint not null references public.menus(id) on delete cascade,
  name text not null,
  description text,
  price numeric(10, 2) not null check (price >= 0),
  image_url text,
  is_available boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.menu_items drop constraint if exists menu_items_name_not_empty;
alter table public.menu_items add constraint menu_items_name_not_empty
  check (length(trim(name)) > 0);

create table if not exists public.restaurant_menu_days (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  menu_item_id bigint not null references public.menu_items(id) on delete cascade,
  menu_date date not null default current_date,
  created_at timestamptz not null default now(),
  unique (restaurant_id, menu_item_id, menu_date)
);

create table if not exists public.restaurant_hours (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  opens_at time,
  closes_at time,
  is_closed boolean not null default false,
  unique (restaurant_id, day_of_week)
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  label text,
  category text not null default 'Autre',
  amount numeric(10, 2) not null check (amount > 0),
  expense_date date not null default current_date,
  description text,
  created_at timestamptz not null default now()
);

alter table public.expenses add column if not exists description text;
alter table public.expenses alter column label drop not null;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'expenses' and column_name = 'notes'
  ) then
    execute 'update public.expenses set description = coalesce(description, notes)';
  end if;
end $$;

alter table public.expenses enable row level security;

create table if not exists public.debts (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  creditor text not null,
  amount numeric(10, 2) not null check (amount > 0),
  description text,
  debt_date date not null default current_date,
  paid_at timestamptz,
  debt_type text not null default 'Je dois'
    check (debt_type in ('Je dois', 'On me doit')),
  status text not null default 'À payer' check (status in ('À payer', 'Payée')),
  created_at timestamptz not null default now()
);

alter table public.debts add column if not exists paid_at timestamptz;
alter table public.debts add column if not exists debt_type text not null default 'Je dois';
alter table public.debts drop constraint if exists debts_debt_type_check;
alter table public.debts add constraint debts_debt_type_check
  check (debt_type in ('Je dois', 'On me doit'));

create or replace function public.prevent_paid_debt_reopening()
returns trigger
language plpgsql
as $$
begin
  if old.status = 'Payée' and new.status <> 'Payée' then
    raise exception 'Une dette payée ne peut pas être réouverte';
  end if;
  return new;
end;
$$;

drop trigger if exists debts_prevent_reopening on public.debts;
create trigger debts_prevent_reopening
  before update on public.debts
  for each row execute function public.prevent_paid_debt_reopening();

alter table public.debts enable row level security;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete restrict,
  customer_name text not null,
  customer_phone text not null,
  delivery_address text,
  notes text,
  status text not null default 'En attente'
    check (status in ('En attente', 'Confirmée', 'En préparation', 'Prête', 'Livrée', 'Annulée')),
  total_amount numeric(10, 2) not null default 0 check (total_amount >= 0),
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists delivery_fee numeric(10, 2) not null default 0 check (delivery_fee >= 0);
alter table public.orders add column if not exists payment_method text not null default 'sur_place';
alter table public.orders add column if not exists notes text;

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_item_id bigint not null references public.menu_items(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null check (unit_price >= 0)
);

alter table public.menus enable row level security;
alter table public.menu_items enable row level security;
alter table public.restaurant_menu_days enable row level security;
alter table public.restaurant_hours enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'restaurants'
  ) then
    alter publication supabase_realtime add table public.restaurants;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'menus'
  ) then
    alter publication supabase_realtime add table public.menus;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'menu_items'
  ) then
    alter publication supabase_realtime add table public.menu_items;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'restaurant_menu_days'
  ) then
    alter publication supabase_realtime add table public.restaurant_menu_days;
  end if;
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'orders'
    ) then
      alter publication supabase_realtime add table public.orders;
    end if;
end $$;

drop policy if exists "Menus publics lisibles par tous" on public.menus;
create policy "Menus publics lisibles par tous"
  on public.menus for select using (true);

drop policy if exists "Menus modifiables en démonstration" on public.menus;
create policy "Menus modifiables en démonstration"
  on public.menus for all using (true) with check (true);

drop policy if exists "Plats publics lisibles par tous" on public.menu_items;
create policy "Plats publics lisibles par tous"
  on public.menu_items for select using (true);

drop policy if exists "Menus du jour publics lisibles par tous" on public.restaurant_menu_days;
create policy "Menus du jour publics lisibles par tous"
  on public.restaurant_menu_days for select using (true);

drop policy if exists "Menus du jour modifiables en démonstration" on public.restaurant_menu_days;
create policy "Menus du jour modifiables en démonstration"
  on public.restaurant_menu_days for all using (true) with check (true);

drop policy if exists "Plats modifiables en démonstration" on public.menu_items;
create policy "Plats modifiables en démonstration"
  on public.menu_items for all using (true) with check (true);

drop policy if exists "Horaires publics lisibles par tous" on public.restaurant_hours;
create policy "Horaires publics lisibles par tous"
  on public.restaurant_hours for select using (true);

drop policy if exists "Dépenses lisibles par le restaurateur" on public.expenses;
create policy "Dépenses lisibles par le restaurateur"
  on public.expenses for select to anon, authenticated using (true);

drop policy if exists "Dépenses créables par le restaurateur" on public.expenses;
create policy "Dépenses créables par le restaurateur"
  on public.expenses for insert to anon, authenticated with check (true);

drop policy if exists "Dettes lisibles par le restaurateur" on public.debts;
create policy "Dettes lisibles par le restaurateur"
  on public.debts for select to anon, authenticated using (true);

drop policy if exists "Dettes créables par le restaurateur" on public.debts;
create policy "Dettes créables par le restaurateur"
  on public.debts for insert to anon, authenticated with check (true);

drop policy if exists "Dettes modifiables par le restaurateur" on public.debts;
create policy "Dettes modifiables par le restaurateur"
  on public.debts for update to anon, authenticated using (true) with check (true);

drop policy if exists "Commandes publiques créables" on public.orders;
create policy "Commandes publiques créables"
  on public.orders for insert to anon, authenticated with check (true);

drop policy if exists "Commandes publiques retournables" on public.orders;
create policy "Commandes publiques retournables"
  on public.orders for select to anon, authenticated using (true);

drop policy if exists "Commandes modifiables par le restaurateur" on public.orders;
create policy "Commandes modifiables par le restaurateur"
  on public.orders for update to anon, authenticated using (true) with check (true);

drop policy if exists "Lignes de commande publiques créables" on public.order_items;
create policy "Lignes de commande publiques créables"
  on public.order_items for insert to anon, authenticated with check (true);

drop policy if exists "Lignes de commande consultables pour le suivi" on public.order_items;
create policy "Lignes de commande consultables pour le suivi"
  on public.order_items for select to anon, authenticated using (true);
  create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  label text not null,
  category text not null default 'Autre',
  amount numeric(10, 2) not null check (amount > 0),
  expense_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.expenses enable row level security;

drop policy if exists "Dépenses lisibles par le restaurateur"
on public.expenses;

create policy "Dépenses lisibles par le restaurateur"
on public.expenses
for select
to anon, authenticated
using (true);

drop policy if exists "Dépenses créables par le restaurateur"
on public.expenses;

create policy "Dépenses créables par le restaurateur"
on public.expenses
for insert
to anon, authenticated
with check (true);