create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'Fermé' check (status in ('Ouvert', 'Fermé')),
  featured_dish text not null,
  tag text not null,
  created_at timestamptz not null default now()
);

alter table public.restaurants add column if not exists phone text;
alter table public.restaurants add column if not exists address text;
alter table public.restaurants add column if not exists position text;
alter table public.restaurants add column if not exists photo_url text;
alter table public.restaurants add column if not exists owner_email text;

alter table public.restaurants enable row level security;

drop policy if exists "Restaurants publics lisibles par tous" on public.restaurants;
create policy "Restaurants publics lisibles par tous"
  on public.restaurants
  for select
  using (true);

drop policy if exists "Restaurants administrables en démonstration" on public.restaurants;
create policy "Restaurants administrables en démonstration"
  on public.restaurants for all using (true) with check (true);


create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists menus_one_active_per_restaurant
  on public.menus (restaurant_id)
  where is_active = true;

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  menu_id bigint not null references public.menus(id) on delete cascade,
  name text not null,
  description text,
  price numeric(10, 2) not null check (price >= 0),
  image_url text,
  is_available boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.menu_items drop constraint if exists menu_items_name_not_empty;
alter table public.menu_items add constraint menu_items_name_not_empty
  check (length(trim(name)) > 0);

create table if not exists public.restaurant_menu_days (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  menu_item_id bigint not null references public.menu_items(id) on delete cascade,
  menu_date date not null default current_date,
  created_at timestamptz not null default now(),
  unique (restaurant_id, menu_item_id, menu_date)
);

create table if not exists public.restaurant_hours (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  opens_at time,
  closes_at time,
  is_closed boolean not null default false,
  unique (restaurant_id, day_of_week)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete restrict,
  customer_name text not null,
  customer_phone text not null,
  delivery_address text,
  status text not null default 'En attente'
    check (status in ('En attente', 'Confirmée', 'En préparation', 'Prête', 'Livrée', 'Annulée')),
  total_amount numeric(10, 2) not null default 0 check (total_amount >= 0),
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists delivery_fee numeric(10, 2) not null default 0 check (delivery_fee >= 0);
alter table public.orders add column if not exists payment_method text not null default 'sur_place';

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_item_id bigint not null references public.menu_items(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null check (unit_price >= 0)
);

alter table public.menus enable row level security;
alter table public.menu_items enable row level security;
alter table public.restaurant_menu_days enable row level security;
alter table public.restaurant_hours enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'restaurants'
  ) then
    alter publication supabase_realtime add table public.restaurants;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'menus'
  ) then
    alter publication supabase_realtime add table public.menus;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'menu_items'
  ) then
    alter publication supabase_realtime add table public.menu_items;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'restaurant_menu_days'
  ) then
    alter publication supabase_realtime add table public.restaurant_menu_days;
  end if;
end $$;

drop policy if exists "Menus publics lisibles par tous" on public.menus;
create policy "Menus publics lisibles par tous"
  on public.menus for select using (true);

drop policy if exists "Menus modifiables en démonstration" on public.menus;
create policy "Menus modifiables en démonstration"
  on public.menus for all using (true) with check (true);

drop policy if exists "Plats publics lisibles par tous" on public.menu_items;
create policy "Plats publics lisibles par tous"
  on public.menu_items for select using (true);

drop policy if exists "Menus du jour publics lisibles par tous" on public.restaurant_menu_days;
create policy "Menus du jour publics lisibles par tous"
  on public.restaurant_menu_days for select using (true);

drop policy if exists "Menus du jour modifiables en démonstration" on public.restaurant_menu_days;
create policy "Menus du jour modifiables en démonstration"
  on public.restaurant_menu_days for all using (true) with check (true);

drop policy if exists "Plats modifiables en démonstration" on public.menu_items;
create policy "Plats modifiables en démonstration"
  on public.menu_items for all using (true) with check (true);

drop policy if exists "Horaires publics lisibles par tous" on public.restaurant_hours;
create policy "Horaires publics lisibles par tous"
  on public.restaurant_hours for select using (true);

drop policy if exists "Commandes publiques créables" on public.orders;
create policy "Commandes publiques créables"
  on public.orders for insert to anon, authenticated with check (true);

drop policy if exists "Commandes publiques retournables" on public.orders;
create policy "Commandes publiques retournables"
  on public.orders for select to anon, authenticated using (true);

drop policy if exists "Lignes de commande publiques créables" on public.order_items;
create policy "Lignes de commande publiques créables"
  on public.order_items for insert to anon, authenticated with check (true);