create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'Fermé' check (status in ('Ouvert', 'Fermé')),
  featured_dish text not null,
  tag text not null,
  created_at timestamptz not null default now()
);

alter table public.restaurants enable row level security;

drop policy if exists "Restaurants publics lisibles par tous" on public.restaurants;
create policy "Restaurants publics lisibles par tous"
  on public.restaurants
  for select
  using (true);

insert into public.restaurants (name, status, featured_dish, tag)
select seed.name, seed.status, seed.featured_dish, seed.tag
from (values
  ('Restaurant Samba', 'Ouvert', 'Fromage + riz', 'Aujourd’hui'),
  ('Le Petit Délice', 'Ouvert', 'Thieboudienne', 'Menu du jour'),
  ('Nour Chez Ali', 'Fermé', 'Poisson grillé', 'Bientôt')
) as seed(name, status, featured_dish, tag)
where not exists (
  select 1 from public.restaurants existing where existing.name = seed.name
);

create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  menu_id bigint not null references public.menus(id) on delete cascade,
  name text not null,
  description text,
  price numeric(10, 2) not null check (price >= 0),
  image_url text,
  is_available boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.restaurant_hours (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  opens_at time,
  closes_at time,
  is_closed boolean not null default false,
  unique (restaurant_id, day_of_week)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete restrict,
  customer_name text not null,
  customer_phone text not null,
  delivery_address text,
  status text not null default 'En attente'
    check (status in ('En attente', 'Confirmée', 'En préparation', 'Prête', 'Livrée', 'Annulée')),
  total_amount numeric(10, 2) not null default 0 check (total_amount >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_item_id bigint not null references public.menu_items(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null check (unit_price >= 0)
);

alter table public.menus enable row level security;
alter table public.menu_items enable row level security;
alter table public.restaurant_hours enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Menus publics lisibles par tous" on public.menus;
create policy "Menus publics lisibles par tous"
  on public.menus for select using (true);

drop policy if exists "Plats publics lisibles par tous" on public.menu_items;
create policy "Plats publics lisibles par tous"
  on public.menu_items for select using (true);

drop policy if exists "Horaires publics lisibles par tous" on public.restaurant_hours;
create policy "Horaires publics lisibles par tous"
  on public.restaurant_hours for select using (true);

drop policy if exists "Commandes publiques créables" on public.orders;
create policy "Commandes publiques créables"
  on public.orders for insert with check (true);

drop policy if exists "Lignes de commande publiques créables" on public.order_items;
create policy "Lignes de commande publiques créables"
  on public.order_items for insert with check (true);